<?php

use Magento\Framework\View\Element\Template;

/**
 * @var $block Template
 */
?>

<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= __('PDF Report') ?></title>
    <style>
        @page {
            size: A4;
            margin: 20mm 15mm;
        }
        *{
            font-family: "DejaVu Sans", sans-serif;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 14px;
            line-height: 1.6;
        }

        /* Хедер */
        .header {
            width: 100%;
            align-items: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .header .logo {
            width: 50%;
            height: 100px;
        }
        .header .qr {
            width: 50%;
            text-align: right;
            height: 100px;
        }
        .header .logo img {
            max-width: 100%;
            height: 100px;
        }

        .header td{
            width: 50%;
        }

        .details {
            margin-top: 10px;
            font-size: 12px;
        }

        /* Основна секція */
        .report {
            margin: 20px 0;
        }
        .report h2 {
            text-align: center;
            margin-bottom: 10px;
        }
        .report table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .report table, .report th, .report td {
            border: 1px solid black;
        }
        .report th, .report td {
            padding: 8px;
            text-align: left;
        }
        .page-break {
            page-break-before: always;
        }

        /* Футер */
        .footer {
            border-top: 2px solid #000;
            margin-top: 20px;
            padding-top: 10px;
            font-size: 12px;
            text-align: center;
        }
    </style>
</head>
<body>
<?= /* @noEscape */ $block->getData('content') ?>
</body>
</html>
