<?php

use Magento\Framework\View\Element\Template;
use SapientPro\Core\ViewModel\CompanyInfoProvider;

/**
 * Report PDF
 *
 * @var $escaper Magento\Framework\Escaper
 * @var $block Template
 * @var $companyInfoProvider \SapientPro\Core\ViewModel\Report\HeaderQr
 */
$companyInfoProvider = $block->getData('report_pdf_qr_view_modal');
?>

<img class="qr-image" alt="<?= __('Company Logo') ?>" src="<?= $companyInfoProvider->generateQrCode($block->getData('unique_document_url') ?? '') ?>"/>
