<?php

use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 */
?>

<section class="page-solutions">
    <div class="row">
        <div class="col-m-4 solution-item">
            <div class="fieldset-wrapper customer-information">
                <div class="fieldset-wrapper-title">
                    <span class="title">SapientPro Core</span>
                </div>
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th><?= __('System requirements') ?>:</th>
                        <td>Magento 2.4.x</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <strong><?= __('Description') ?></strong><br>
                    <p>
                        <i class="sapientpro-logo large"></i>
                        Tune your Magento solution with our extension and reach our modules within a few clicks on your dashboards. With this module, you get access to other extensions we’ve developed for you. It’s like a special portal to our services, and if you like what we do - feel free to contact us. All the extensions are free as SapientPro’s aim is to share what we can do!
                        As soon as you download this extension, our logo will appear on your Magento menu. Click it, and we’ll redirect you to our other solutions. Get access to our website and contacts. Code sapiently, develop like a pro!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-m-4 solution-item">
            <div class="fieldset-wrapper customer-information">
                <div class="fieldset-wrapper-title">
                    <span class="title">Point Of Sale</span>
                </div>
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th><?= __('System requirements') ?>:</th>
                        <td>Magento 2.4.x</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <strong><?= __('Description') ?></strong><br>
                    <p>
                        <i class="sapientpro-logo large"></i>
                        This POS extension for Magento 2 helps you unify online and in-store sales, facilitating smooth checkouts across multiple store locations.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-m-4 solution-item">
            <div class="fieldset-wrapper customer-information">
                <div class="fieldset-wrapper-title">
                    <span class="title">Funds Manager</span>
                </div>
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th><?= __('System requirements') ?>:</th>
                        <td>Magento 2.4.x</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <strong><?= __('Description') ?></strong><br>
                    <p>
                        <i class="sapientpro-logo large"></i>
                        coming soon...
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
