<?php
/**
 * SapientPro
 *
 * @category    SapientPro
 * @package     SapientPro_Core
 * @author      SapientPro Team <info@sapient.pro >
 * @copyright   Copyright © 2009-2019 SapientPro (https://sapient.pro)
 */
?>

<section class="page-solutions">
    <div class="row">
        <div class="col-m-4 solution-item">
            <div class="fieldset-wrapper customer-information">
                <div class="fieldset-wrapper-title">
                    <span class="title">SapientPro Core</span>
                </div>
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th><?= __('Type') ?>:</th>
                        <td>Magento 2 module</td>
                    </tr>
                    <tr>
                        <th><?= __('Latest Version') ?>:</th>
                        <td>1.0.0</td>
                    </tr>
                    <tr>
                        <th><?= __('License') ?>:</th>
                        <td>MIT</td>
                    </tr>
                    <tr>
                        <th><?= __('System requirements') ?>:</th>
                        <td>Magento 2.3.X, php >= 7.0</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <strong><?= __('Description') ?></strong><br>
                    <p>
                        <i class="sapientpro-logo large"></i>
                        Tune your Magento solution with our extension and reach our modules within a few clicks on your dashboards. With this module, you get access to other extensions we’ve developed for you. It’s like a special portal to our services, and if you like what we do - feel free to contact us. All the extensions are free as SapientPro’s aim is to share what we can do!
                        As soon as you download this extension, our logo will appear on your Magento menu. Click it, and we’ll redirect you to our other solutions. Get access to our website and contacts. Code sapiently, develop like a pro!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-m-4 solution-item">
            <div class="fieldset-wrapper customer-information">
                <div class="fieldset-wrapper-title">
                    <span class="title">Facebook SDK</span>
                </div>
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th><?= __('Type') ?>:</th>
                        <td>Magento 2 module</td>
                    </tr>
                    <tr>
                        <th><?= __('Latest Version') ?>:</th>
                        <td>1.0.0</td>
                    </tr>
                    <tr>
                        <th><?= __('License') ?>:</th>
                        <td>MIT</td>
                    </tr>
                    <tr>
                        <th><?= __('System requirements') ?>:</th>
                        <td>Magento 2.3.X, SapientPro Core Module, php >= 7.0</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <strong><?= __('Description') ?></strong><br>
                    <p>
                        <i class="sapientpro-logo large"></i>
                        With Facebook Software Development Kit, you reach a new level of social media presence.
                        Each E-Commerce solution must be well introduced in social media, as the most target audience
                        spends time there. Show them how great your products are with the ads and do it fast and
                        efficiently with our extension. Then gather data about the user’s activity with your promoted
                        posts and find out what works best with the audience and what - does not. Our Facebook SDK
                        contains a lot of components that help to do all of that, and even more. We integrate it with
                        your Magento and it’s ready to boost your project. Plug and play, as they say!
                    </p>
                </div>
            </div>
        </div>
        <div class="col-m-4 solution-item">
            <div class="fieldset-wrapper customer-information">
                <div class="fieldset-wrapper-title">
                    <span class="title">Facebook Login</span>
                </div>
                <table class="admin__table-secondary">
                    <tbody>
                    <tr>
                        <th><?= __('Type') ?>:</th>
                        <td>Magento 2 module</td>
                    </tr>
                    <tr>
                        <th><?= __('Latest Version') ?>:</th>
                        <td>1.0.0</td>
                    </tr>
                    <tr>
                        <th><?= __('License') ?>:</th>
                        <td>MIT</td>
                    </tr>
                    <tr>
                        <th><?= __('System requirements') ?>:</th>
                        <td>Magento 2.3.X, SapientPro Core Module, php >= 7.0</td>
                    </tr>
                    </tbody>
                </table>
                <div class="description">
                    <strong><?= __('Description') ?></strong><br>
                    <p>
                        <i class="sapientpro-logo large"></i>
                        Let your users log in quickly by implementing Facebook Login Module for Magento. After the
                        installation is finished, the login button will appear on the registration page and anywhere
                        it is needed to check out on your website. Our solution stands out with its flexibility and
                        details. We correctly met all the requirements of Facebook, and so there won’t be any problems
                        with their inside rules. We don’t want just the quantity; we strive for quality.
                        That’s why we perfected this simple solution.
                        With our Facebook login extension, your users will be more willing to register, and that means
                        a boost in the number of customers, which leads to traffic and sales increase.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
